export const LOAD_FILME_SUCCESS = 'LOAD_FILME_SUCCESS';
export const UPDATE_FILM_SUCCESS = 'UPDATE_FILM_SUCCESS';
export const CREATE_FILM_SUCCESS = 'CREATE_FILM_SUCCESS';
export const DELETE_FILM_SUCCESS = 'DELETE_FILM_SUCCESS';

